/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wofjGBAYZzY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function test_grad() {
  return (
    <div className="w-full flex items-center justify-center text-4xl font-bold bg-gradient-to-r from-[#93C5FD] to-[#EFF6FF] text-transparent bg-clip-text">
      Welcome to our website
    </div>
  )
}
